[package]
name = "mathematx"
version = "0.1.0"
edition = "2021"

[dependencies]
criterion = "0.4"
rayon = "1.5"

[dev-dependencies]
serde_json = "1"

[[bench]]
name = "hashing_murmur3"
harness = false

[[bench]]
name = "hashing_fnv1"
harness = false

[[bench]]
name = "hashing_fnv1a"
harness = false